---
- name: Testing andrewrothstein.groovy
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'groovy version'
      ansible.builtin.command: sh -l -c 'groovy --version'
      changed_when: false
      register: groovy_test_output
    - name: Output from 'groovy version'
      ansible.builtin.debug:
        msg: '{{ groovy_test_output.stdout }}'
