---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jdk
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for existing install in {{ groovy_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ groovy_install_dir }}'
  changed_when: false
  register: groovy_binary
- name: Downloading and installing groovy
  when: not groovy_binary.stat.exists
  block:
    - name: Downloading {{ groovy_url }} to {{ groovy_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ groovy_url }}'
        dest: '{{ groovy_tmp_zip }}'
        checksum: '{{ groovy_checksum }}'
        mode: '644'
    - name: Unarchiving {{ groovy_tmp_zip }} to {{ groovy_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ groovy_tmp_zip }}'
        dest: '{{ groovy_parent_install_dir }}'
        creates: '{{ groovy_install_dir }}'
  always:
    - name: Rm {{ groovy_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ groovy_tmp_zip }}'
        state: absent
- name: Linking {{ groovy_link_dir }} to {{ groovy_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ groovy_install_dir }}'
    dest: '{{ groovy_link_dir }}'
    state: link
- name: Adding groovy to default login shell path
  become: true
  become_user: root
  with_items:
    - f: groovy.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: 0644
